### ISSUE TITLE
Error when upgrading to 6.2.3

### ISSUE THREAD

**Issue by rosebm** [pollfish/android-sdk-pollfish#16]
Hi!

Currently our app is running with Pollfish v6.1.5, now trying to upgrade to v6.2.3, we're getting:

```
The binary version of its metadata is 1.6.0, expected version is 1.4.2.
The class is loaded from /root/.gradle/caches/transforms-3/e1f4ffecf7f54c1cb2513e58154184a3/transformed/jetified-kotlin-stdlib-1.6.10.jar!/kotlin/Unit.class
> Task :app:compileDebugKotlin FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
```

If I downgrade to v.6.1.5, the app build with no issues. Do you know what could be the cause?

**Comment by fotism23** [comment]
Hello @rosebm 

What's your current Kotlin version?

**Comment by rosebm** [comment]
Is 1.4.31

**Comment by fotism23** [comment]
Please try upgrading Kotlin to 1.6.10 if possible

**Comment by rosebm** [comment]
With kotlin updated, another errors are being shown now:

```
 warning: There are multiple good constructors and Room will pick the no-arg constructor. You can use the @Ignore annotation to eliminate unwanted constructors.
public final class TransactionExtrasEntity {
             ^
TransactionExtrasEntity.java:11: error: Cannot find setter for field.
    private final java.lang.String creativeId = null;

AlertDao.java:27: error: Not sure how to handle insert method's return type.
    public abstract java.lang.Object insert(@org.jetbrains.annotations.NotNull()
                                     ^

> Task :app:kaptDebugKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)

```

![Screen Shot 2022-04-13 at 10 23 49 AM](https://user-images.githubusercontent.com/6003620/163214367-5c5fa7bf-e182-4e05-a022-39dea3ec3f70.png)

**Comment by rosebm** [comment]
We'll work on some dependencies updates and let you know the results. Thank you!

**Comment by rosebm** [comment]
Hi @fotism23 ! 
We were able to upgrade Pollfish to 6.2.4, it was a chain of dependencies that also needed to be upgraded as well and now running with no issues.

Thanks.

**Comment by fotism23** [comment]
Great news @rosebm 
Thanks for the update
